[gcloud]
disabled = true

[package]
disabled = true

[vagrant]
disabled = true

[git_status]
modified = '✎'
staged = '+'
stashed = ''

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

